[package]
name = "dga"
version = "0.1.0"
edition = "2021"

[dependencies]
icons.workspace = true
assets.workspace = true
magnet.workspace = true

ui.workspace = true
gpui.workspace = true
reqwest_client.workspace = true
