name: Rust Build and Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run-test:
    name: run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@master

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            libgtk-3-dev \
            libsoup-3.0-dev \
            javascriptcoregtk-4.1-dev \
            libwebkit2gtk-4.1-dev \
            libxkbcommon-x11-dev

      - name: Run test
        run: |
          cargo test --all-features --color always
